### ISSUE TITLE
Split this module up into main pluggable API and plugins

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/signature-algorithms#2]
This module should be split up so there's a main API for registering and getting signature algorithms -- and the individual algorithms, with each individual algorithm getting its own installable module.

See comments on #1.

**Comment by mattcollier** [comment]
Low priority, but I'm curious about the future of this module and what the intersections are with crypto-ld etc.  I wonder if the suggested pluggable architecture is in keeping with the latest design paradigm.

**Comment by aljones15** [comment]
@dlongley this module needs to be updated in order to be used with the http-sig spec tests. permissions to update this?

**Comment by dlongley** [comment]
@aljones15, I don't know if we're even using this anywhere anymore. We might *only* be using it in one place, the http-signature stuff ... and I believe we may have had to even avoid using it on the client because it was node-only. So, I can't really look into this right now, but it's possible we don't plan on maintaining this because it has been replaced by other things.

**Comment by aljones15** [comment]
if that is the case that is great because I removed it from the http-signatures binary today.

**Comment by dlongley** [comment]
Closing to archive repo.
